# -*- coding: utf-8 -*-
"""
ISO/TR 16224:2012 bolt-nut tensile failure calculator V13
=========================================================

Outputs per case folder:
  1) <CASE_NAME>_drawing.pdf      -> drawing only (CAD-style geometry/dimensions)
  2) <CASE_NAME>_calculation.md   -> 中文公式、代入过程、结果和警告

Key user-requested behavior:
- Nut height m can be generated by ratio m = k_m * D (default k_m=0.8),
  or supplied as a custom value.
- Thread angle is user-defined.
- Profile truncation coefficients are user-defined.
- ISO/TR 16224 correction factors are only applied in the ranges explicitly
  given by the report. When a correction term is outside its stated range,
  that correction is ignored (factor = 1.0), and the MD report warns that
  accuracy/applicability is reduced and a larger safety factor should be
  considered by the designer.
- PDF contains drawings only; all calculation text/formulas are written to MD.

Units:
- length: mm
- stress: MPa = N/mm^2
- force: N (MD also reports kN)
"""

from pathlib import Path
import math
import hashlib

# ============================================================================
# Python 3.7 + newer ReportLab compatibility
# ============================================================================
# Some newer ReportLab versions call:
#     hashlib.md5(..., usedforsecurity=False)
# but Python 3.7's OpenSSL-backed hashlib.md5() does not accept the
# "usedforsecurity" keyword, producing:
#     TypeError: openssl_md5() takes no keyword arguments
#
# Patch hashlib.md5 BEFORE importing ReportLab. The extra keyword is only a
# compatibility/security-policy hint; removing it does not change the MD5
# digest ReportLab uses internally for PDF document IDs.
_original_hashlib_md5 = hashlib.md5

def _md5_py37_compat(*args, **kwargs):
    kwargs.pop("usedforsecurity", None)
    return _original_hashlib_md5(*args, **kwargs)

hashlib.md5 = _md5_py37_compat

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A3, landscape
from reportlab.lib.units import mm


# ============================================================================
# 1. OUTPUT SETTINGS / 输出设置
# ============================================================================

# Root output directory. Can be absolute or relative.
OUTPUT_BASE_DIR = Path(r"./ISO_TR_16224_outputs")

# Subfolder name and output filename prefix for this case.
CASE_NAME = "M60x3_demo"

# The program creates:
#   OUTPUT_BASE_DIR / CASE_NAME / f"{CASE_NAME}_drawing.pdf"
#   OUTPUT_BASE_DIR / CASE_NAME / f"{CASE_NAME}_calculation.md"


# ============================================================================
# 2. USER INPUT / 用户输入
# ============================================================================

# Labels only; no material/thread database is used.
bolt_property_class = "10.9"
nut_property_class = "10"

# Safety factor (engineering post-processing, not an original ISO/TR load formula)
safety_factor = 2

# Material tensile strengths
Rm = 1000.0       # bolt tensile strength, MPa
Rmn = 800.0       # nut/internal-thread material tensile strength, MPa

# Thread main geometry
d = 60.0              # nominal major diameter d (= D for mating thread), mm
P = 3.0               # pitch, mm
thread_angle = 60.0   # included thread angle, deg; not forced to 60

# Thread-profile truncation coefficients, relative to H
k_flat = 1.0 / 8.0            # flat truncation height = k_flat * H
k_external_root = 1.0 / 6.0   # external root equivalent truncation = coeff * H
k_internal_crest = 1.0 / 4.0  # internal crest truncation = coeff * H

# Nut width across flats
s = 90.0          # mm

# Nut height mode:
#   "ratio"  -> m = nut_height_ratio * D; default common design value = 0.8D
#   "custom" -> m = nut_height_custom
nut_height_mode = "ratio"
nut_height_ratio = 0.80
nut_height_custom = 30.0   # mm; used only when nut_height_mode == "custom"

# Chamfer geometry
hc = 2.0          # chamfer height per end, mm
chamfer_ends = 2  # 1 = one-end chamfer, 2 = both-end chamfer

# Drawing-only countersink/chamfer included angle; not used in strength formulas
drawing_countersink_included_angle = 90.0


# ============================================================================
# 3. INPUT VALIDATION AND GEOMETRY
# ============================================================================

def validate_inputs():
    if d <= 0 or P <= 0:
        raise ValueError("d and P must be > 0")
    if not (0 < thread_angle < 180):
        raise ValueError("thread_angle must satisfy 0 < angle < 180 deg")
    if Rm <= 0 or Rmn <= 0:
        raise ValueError("Rm and Rmn must be > 0")
    if safety_factor <= 0:
        raise ValueError("safety_factor must be > 0")
    if s <= 0:
        raise ValueError("s must be > 0")
    if hc < 0:
        raise ValueError("hc must be >= 0")
    if chamfer_ends not in (1, 2):
        raise ValueError("chamfer_ends must be 1 or 2")
    if nut_height_mode not in ("ratio", "custom"):
        raise ValueError('nut_height_mode must be "ratio" or "custom"')
    if nut_height_ratio <= 0:
        raise ValueError("nut_height_ratio must be > 0")
    if nut_height_custom <= 0:
        raise ValueError("nut_height_custom must be > 0")

    for name, value in (
        ("k_flat", k_flat),
        ("k_external_root", k_external_root),
        ("k_internal_crest", k_internal_crest),
    ):
        if not (0.0 <= value < 1.0):
            raise ValueError(f"{name} must satisfy 0 <= {name} < 1")

    if k_flat + k_external_root >= 1.0:
        raise ValueError("k_flat + k_external_root must be < 1")
    if k_flat + k_internal_crest >= 1.0:
        raise ValueError("k_flat + k_internal_crest must be < 1")


def resolve_nut_height(D_value):
    if nut_height_mode == "ratio":
        return nut_height_ratio * D_value, (
            f"m = nut_height_ratio * D = {nut_height_ratio:.6f} * {D_value:.6f}"
        )
    return nut_height_custom, f"m = nut_height_custom = {nut_height_custom:.6f}"


def thread_dimensions():
    """Parametric symmetric V-thread geometry."""
    alpha2 = math.radians(thread_angle / 2.0)
    tan_half = math.tan(alpha2)
    H = P / (2.0 * tan_half)

    h_flat = k_flat * H
    h_external_root = k_external_root * H
    h_internal_crest = k_internal_crest * H

    d2 = d - 2.0 * (H / 2.0 - h_flat)
    D2 = d2

    d1 = d - 2.0 * (H - h_flat - h_internal_crest)
    D1 = d1

    d3 = d - 2.0 * (H - h_flat - h_external_root)

    if min(d1, d2, d3, D1, D2) <= 0:
        raise ValueError("Calculated thread diameter <= 0; check geometry inputs")

    return {
        "D": d,
        "d": d,
        "H": H,
        "tan_half": tan_half,
        "h_flat": h_flat,
        "h_external_root": h_external_root,
        "h_internal_crest": h_internal_crest,
        "d1": d1,
        "d2": d2,
        "d3": d3,
        "D1": D1,
        "D2": D2,
    }


def effective_nut_height(m_value):
    if chamfer_ends == 1:
        meff = m_value - 0.6 * hc
        formula = "meff = m - 0.6 hc"
    else:
        meff = m_value - 1.2 * hc
        formula = "meff = m - 1.2 hc"
    if meff <= 0:
        raise ValueError("meff <= 0; check m, hc and chamfer_ends")
    return meff, formula


# ============================================================================
# 4. CALCULATION
# ============================================================================

def nominal_stress_area(d2_value, d3_value):
    return math.pi / 4.0 * ((d2_value + d3_value) / 2.0) ** 2


def actual_stress_area(d1_value, d2_value):
    # Confirmed in the user's manual review for this implementation.
    return math.pi / 4.0 * ((d1_value + d2_value) / 2.0) ** 2


def shear_areas(g, meff):
    tan_half = g["tan_half"]
    Dm = 1.026 * g["D1"]

    term1 = (
        (0.6 * meff / P)
        * math.pi
        * g["D1"]
        * (P / 2.0 + (g["d2"] - g["D1"]) * tan_half)
    )
    term2 = (
        (0.4 * meff / P)
        * math.pi
        * Dm
        * (P / 2.0 + (g["d2"] - Dm) * tan_half)
    )
    ASb = term1 + term2

    ASn = (
        (meff / P)
        * math.pi
        * g["d"]
        * (P / 2.0 + (g["d"] - g["D2"]) * tan_half)
    )

    if ASb <= 0 or ASn <= 0:
        raise ValueError("Calculated ASb/ASn <= 0; check thread geometry")

    return Dm, term1, term2, ASb, ASn


def correction_factors(Rs, D_value):
    """
    Range behavior requested by user:
    outside a stated ISO/TR range -> do not extrapolate; ignore that correction,
    i.e. set factor to 1.0 and issue a warning.
    """
    warnings = []
    status = {}
    ratio = s / D_value

    # C1
    if 1.4 <= ratio < 1.9:
        C1 = -(ratio ** 2) + 3.8 * ratio - 2.6
        status["C1"] = (True, f"1.4 <= s/D={ratio:.6f} < 1.9")
    else:
        C1 = 1.0
        msg = (
            f"C1 out of range: s/D={ratio:.6f}; stated range is 1.4 <= s/D < 1.9. "
            "C1 is ignored (set to 1.0)."
        )
        warnings.append(msg)
        status["C1"] = (False, msg)

    # C2
    if Rs <= 1.0:
        C2 = 0.897
        status["C2"] = (True, f"Rs={Rs:.6f} <= 1 -> C2=0.897")
    elif Rs < 2.2:
        C2 = (
            5.594
            - 13.682 * Rs
            + 14.107 * Rs ** 2
            - 6.057 * Rs ** 3
            + 0.9353 * Rs ** 4
        )
        status["C2"] = (True, f"1 < Rs={Rs:.6f} < 2.2 -> Eq.(6) polynomial")
    else:
        C2 = 1.0
        msg = (
            f"C2 out of range: Rs={Rs:.6f} >= 2.2; Eq.(6) gives no formula there. "
            "C2 is ignored (set to 1.0)."
        )
        warnings.append(msg)
        status["C2"] = (False, msg)

    # C3
    if Rs <= 0.4:
        C3 = 1.0
        msg = (
            f"C3 out of range: Rs={Rs:.6f} <= 0.4; Eq.(6) gives no formula there. "
            "C3 is ignored (set to 1.0)."
        )
        warnings.append(msg)
        status["C3"] = (False, msg)
    elif Rs < 1.0:
        C3 = 0.728 + 1.769 * Rs - 2.896 * Rs ** 2 + 1.296 * Rs ** 3
        status["C3"] = (True, f"0.4 < Rs={Rs:.6f} < 1 -> Eq.(6) polynomial")
    else:
        C3 = 0.897
        status["C3"] = (True, f"Rs={Rs:.6f} >= 1 -> C3=0.897")

    if warnings:
        warnings.append(
            "One or more correction terms are outside the stated ISO/TR applicability range. "
            "Model applicability/accuracy is reduced. Consider a larger safety factor and "
            "verification by test or a more appropriate design method."
        )

    return C1, C2, C3, ratio, status, warnings


def calculate():
    validate_inputs()
    g = thread_dimensions()
    m_value, m_formula = resolve_nut_height(g["D"])
    meff, meff_formula = effective_nut_height(m_value)

    As_nom = nominal_stress_area(g["d2"], g["d3"])
    As = actual_stress_area(g["d1"], g["d2"])
    FBb = Rm * As

    Dm, ASb_term1, ASb_term2, ASb, ASn = shear_areas(g, meff)
    Rs = (Rmn * ASn) / (Rm * ASb)

    C1, C2, C3, s_over_D, correction_status, warnings = correction_factors(Rs, g["D"])

    FSb = 0.6 * Rm * ASb * C1 * C2
    FSn = 0.6 * Rmn * ASn * C1 * C3

    loads = {
        "FBb bolt breaking": FBb,
        "FSb bolt-thread stripping": FSb,
        "FSn nut-thread stripping": FSn,
    }
    governing_mode = min(loads, key=loads.get)
    governing_load = loads[governing_mode]
    allowable_load = governing_load / safety_factor

    return {
        "g": g,
        "m": m_value,
        "m_formula": m_formula,
        "meff": meff,
        "meff_formula": meff_formula,
        "As_nom": As_nom,
        "As": As,
        "FBb": FBb,
        "Dm": Dm,
        "ASb_term1": ASb_term1,
        "ASb_term2": ASb_term2,
        "ASb": ASb,
        "ASn": ASn,
        "Rs": Rs,
        "C1": C1,
        "C2": C2,
        "C3": C3,
        "s_over_D": s_over_D,
        "correction_status": correction_status,
        "warnings": warnings,
        "FSb": FSb,
        "FSn": FSn,
        "governing_mode": governing_mode,
        "governing_load": governing_load,
        "allowable_load": allowable_load,
    }


# ============================================================================
# 5. MARKDOWN CALCULATION REPORT
# ============================================================================

def build_markdown(r):
    """生成中文 Markdown 计算书：公式、代入过程、结果和适用范围警告。"""
    g = r["g"]
    tan_half = g["tan_half"]
    meff_coeff = 0.6 if chamfer_ends == 1 else 1.2

    mode_cn = "按比例自动计算" if nut_height_mode == "ratio" else "用户自定义"
    chamfer_cn = "单端倒角" if chamfer_ends == 1 else "双端倒角"

    governing_map = {
        "FBb bolt breaking": "螺栓断裂 FBb",
        "FSb bolt-thread stripping": "外螺纹剥牙 FSb",
        "FSn nut-thread stripping": "内螺纹剥牙 FSn",
    }
    governing_cn = governing_map.get(r["governing_mode"], r["governing_mode"])

    lines = [
        f"# ISO/TR 16224:2012 计算书 - {CASE_NAME}",
        "",
        "> 本计算书由程序根据输入参数自动生成。PDF 文件仅保存参数化工程图，本 MD 文件保存完整计算过程。",
        "",
        "## 1. 输入参数",
        "",
        f"- 螺栓等级标签：`{bolt_property_class}`",
        f"- 螺母等级标签：`{nut_property_class}`",
        f"- 螺栓抗拉强度 Rm：`{Rm:.6f} MPa`",
        f"- 螺母/内螺纹材料抗拉强度 Rmn：`{Rmn:.6f} MPa`",
        f"- 公称直径 d = D：`{d:.6f} mm`",
        f"- 螺距 P：`{P:.6f} mm`",
        f"- 螺纹夹角 α：`{thread_angle:.6f}°`",
        f"- 平顶截短系数 k_flat：`{k_flat:.9f}`",
        f"- 外螺纹牙底截短系数 k_external_root：`{k_external_root:.9f}`",
        f"- 内螺纹牙顶截短系数 k_internal_crest：`{k_internal_crest:.9f}`",
        f"- 螺母对边尺寸 s：`{s:.6f} mm`",
        f"- 螺母高度模式：`{mode_cn}`",
        f"- 螺母高度比例：`m = {nut_height_ratio:.6f}D`",
        f"- 自定义螺母高度：`{nut_height_custom:.6f} mm`",
        f"- 每端倒角高度 hc：`{hc:.6f} mm`",
        f"- 倒角形式：`{chamfer_cn}`",
        f"- 安全系数：`{safety_factor:.6f}`",
        "",
        "## 2. 螺母高度",
        "",
    ]

    if nut_height_mode == "ratio":
        lines += [
            r"$$m=k_mD$$",
            f"- 代入：m = {nut_height_ratio:.9f} × {g['D']:.9f}",
            f"- **m = {r['m']:.9f} mm**",
        ]
    else:
        lines += [
            r"$$m=m_{\mathrm{custom}}$$",
            f"- **m = {r['m']:.9f} mm**",
        ]

    lines += [
        "",
        "## 3. 螺纹基本几何",
        "",
        r"$$H=\frac{P}{2\tan(\alpha/2)}$$",
        f"- 代入：H = {P:.9f} / [2 × tan({thread_angle:.9f}° / 2)]",
        f"- **H = {g['H']:.9f} mm**",
        "",
        r"$$h_{flat}=k_{flat}H$$",
        f"- 代入：h_flat = {k_flat:.9f} × {g['H']:.9f}",
        f"- **h_flat = {g['h_flat']:.9f} mm**",
        "",
        r"$$h_{ext.root}=k_{external\_root}H$$",
        f"- 代入：h_ext.root = {k_external_root:.9f} × {g['H']:.9f}",
        f"- **h_ext.root = {g['h_external_root']:.9f} mm**",
        "",
        r"$$h_{int.crest}=k_{internal\_crest}H$$",
        f"- 代入：h_int.crest = {k_internal_crest:.9f} × {g['H']:.9f}",
        f"- **h_int.crest = {g['h_internal_crest']:.9f} mm**",
        "",
        r"$$d_2=D_2=d-2\left(\frac{H}{2}-h_{flat}\right)$$",
        f"- 代入：{d:.9f} - 2 × ({g['H']:.9f}/2 - {g['h_flat']:.9f})",
        f"- **d2 = D2 = {g['d2']:.9f} mm**",
        "",
        r"$$d_1=D_1=d-2(H-h_{flat}-h_{int.crest})$$",
        f"- 代入：{d:.9f} - 2 × ({g['H']:.9f} - {g['h_flat']:.9f} - {g['h_internal_crest']:.9f})",
        f"- **d1 = D1 = {g['d1']:.9f} mm**",
        "",
        r"$$d_3=d-2(H-h_{flat}-h_{ext.root})$$",
        f"- 代入：{d:.9f} - 2 × ({g['H']:.9f} - {g['h_flat']:.9f} - {g['h_external_root']:.9f})",
        f"- **d3 = {g['d3']:.9f} mm**",
        "",
        "### 3.1 PDF 中外螺纹牙底圆弧的绘图几何（仅用于绘图）",
        "",
        "外螺纹牙底圆弧按“与两侧理论牙面相切、圆弧最低点位于 d3 直径处”的条件构造。",
        "该圆弧只改变 PDF 中的几何表达，不参与 FBb、FSb、FSn 的强度公式。",
        "",
        r"设 $$t=\alpha/2,\quad h_r=h_{ext.root}$$",
        r"则相切圆弧半径为：",
        r"$$\rho=\frac{h_r\sin t}{1-\sin t}$$",
        f"- 当前 t = {thread_angle/2.0:.9f}°",
        f"- 当前 h_r = {g['h_external_root']:.9f} mm",
    ]

    sin_half = math.sin(math.radians(thread_angle/2.0))
    if 0.0 < sin_half < 1.0:
        root_radius = g["h_external_root"] * sin_half / (1.0 - sin_half)
        lines += [
            f"- **绘图圆弧半径 ρ = {root_radius:.9f} mm**",
            "",
        ]
    else:
        lines += ["- 当前角度无法形成有限相切圆弧。", ""]

    lines += [
        "## 4. 螺栓断裂",
        "",
        r"$$A_{s,nom}=\frac{\pi}{4}\left(\frac{d_2+d_3}{2}\right)^2$$",
        f"- 代入：π/4 × [({g['d2']:.9f} + {g['d3']:.9f})/2]^2",
        f"- As,nom = **{r['As_nom']:.9f} mm²**",
        "",
        r"$$A_s=\frac{\pi}{4}\left(\frac{d_1+d_2}{2}\right)^2$$",
        f"- 代入：π/4 × [({g['d1']:.9f} + {g['d2']:.9f})/2]^2",
        f"- As = **{r['As']:.9f} mm²**",
        "",
        r"$$F_{Bb}=R_mA_s$$",
        f"- 代入：{Rm:.9f} × {r['As']:.9f}",
        f"- **FBb = {r['FBb']:.6f} N = {r['FBb']/1000:.6f} kN**",
        "",
        "## 5. 有效啮合高度与螺纹剪切面积",
        "",
    ]

    if chamfer_ends == 1:
        lines += [r"$$m_{eff}=m-0.6h_c$$"]
    else:
        lines += [r"$$m_{eff}=m-1.2h_c$$"]

    lines += [
        f"- 代入：{r['m']:.9f} - {meff_coeff:.1f} × {hc:.9f}",
        f"- **meff = {r['meff']:.9f} mm**",
        "",
        r"$$D_m=1.026D_1$$",
        f"- 代入：1.026 × {g['D1']:.9f}",
        f"- **Dm = {r['Dm']:.9f} mm**",
        "",
        f"- tan(α/2) = tan({thread_angle:.9f}°/2) = `{tan_half:.12f}`",
        "",
        "### 5.1 外螺纹剪切面积 ASb",
        "",
        r"$$A_{Sb}=\frac{0.6m_{eff}}{P}\pi D_1\left[\frac{P}{2}+(d_2-D_1)\tan(\alpha/2)\right]"
        r"+\frac{0.4m_{eff}}{P}\pi D_m\left[\frac{P}{2}+(d_2-D_m)\tan(\alpha/2)\right]$$",
        f"- 第一项 = **{r['ASb_term1']:.9f} mm²**",
        f"- 第二项 = **{r['ASb_term2']:.9f} mm²**",
        f"- **ASb = {r['ASb_term1']:.9f} + {r['ASb_term2']:.9f} = {r['ASb']:.9f} mm²**",
        "",
        "### 5.2 内螺纹剪切面积 ASn",
        "",
        r"$$A_{Sn}=\frac{m_{eff}}{P}\pi d\left[\frac{P}{2}+(d-D_2)\tan(\alpha/2)\right]$$",
        f"- 代入：({r['meff']:.9f}/{P:.9f}) × π × {d:.9f} × [{P:.9f}/2 + ({d:.9f}-{g['D2']:.9f}) × {tan_half:.12f}]",
        f"- **ASn = {r['ASn']:.9f} mm²**",
        "",
        "## 6. 强度比与修正系数",
        "",
        r"$$R_s=\frac{R_{mn}A_{Sn}}{R_mA_{Sb}}$$",
        f"- 代入：({Rmn:.9f} × {r['ASn']:.9f}) / ({Rm:.9f} × {r['ASb']:.9f})",
        f"- **Rs = {r['Rs']:.12f}**",
        "",
        f"- s/D = {s:.9f}/{g['D']:.9f} = **{r['s_over_D']:.12f}**",
        "",
        "### C1：螺母胀大修正",
        "",
        "标准给定范围：`1.4 <= s/D < 1.9`",
    ]

    applied_c1 = r["correction_status"]["C1"][0]
    if applied_c1:
        lines += [
            r"$$C_1=-(s/D)^2+3.8(s/D)-2.6$$",
            f"- 当前 s/D = {r['s_over_D']:.12f}，在适用范围内",
            f"- **C1 = {r['C1']:.12f}**",
        ]
    else:
        lines += [
            f"- 当前 s/D = {r['s_over_D']:.12f}，超出适用范围",
            "- 按本程序规则：不外推该修正项，取 **C1 = 1.0**",
        ]

    lines += [
        "",
        "### C2：外螺纹弯曲修正",
        "",
        "- Rs <= 1：C2 = 0.897",
        "- 1 < Rs < 2.2：采用 ISO/TR 16224 式(6)四次多项式",
    ]

    applied_c2 = r["correction_status"]["C2"][0]
    if applied_c2:
        if r["Rs"] <= 1.0:
            lines += [f"- 当前 Rs = {r['Rs']:.12f} <= 1", f"- **C2 = {r['C2']:.12f}**"]
        else:
            lines += [
                r"$$C_2=5.594-13.682R_s+14.107R_s^2-6.057R_s^3+0.9353R_s^4$$",
                f"- 当前 Rs = {r['Rs']:.12f}，位于 1 < Rs < 2.2",
                f"- **C2 = {r['C2']:.12f}**",
            ]
    else:
        lines += [
            f"- 当前 Rs = {r['Rs']:.12f} >= 2.2，标准未给出该区间 C2 公式",
            "- 按本程序规则：不外推，取 **C2 = 1.0**",
        ]

    lines += [
        "",
        "### C3：内螺纹弯曲修正",
        "",
        "- 0.4 < Rs < 1：采用 ISO/TR 16224 式(6)三次多项式",
        "- Rs >= 1：C3 = 0.897",
    ]

    applied_c3 = r["correction_status"]["C3"][0]
    if applied_c3:
        if r["Rs"] >= 1.0:
            lines += [f"- 当前 Rs = {r['Rs']:.12f} >= 1", f"- **C3 = {r['C3']:.12f}**"]
        else:
            lines += [
                r"$$C_3=0.728+1.769R_s-2.896R_s^2+1.296R_s^3$$",
                f"- 当前 Rs = {r['Rs']:.12f}，位于 0.4 < Rs < 1",
                f"- **C3 = {r['C3']:.12f}**",
            ]
    else:
        lines += [
            f"- 当前 Rs = {r['Rs']:.12f} <= 0.4，标准未给出该区间 C3 公式",
            "- 按本程序规则：不外推，取 **C3 = 1.0**",
        ]

    lines += [
        "",
        "## 7. 外螺纹与内螺纹剥牙载荷",
        "",
        r"$$F_{Sb}=0.6R_mA_{Sb}C_1C_2$$",
        f"- 代入：0.6 × {Rm:.9f} × {r['ASb']:.9f} × {r['C1']:.12f} × {r['C2']:.12f}",
        f"- **FSb = {r['FSb']:.6f} N = {r['FSb']/1000:.6f} kN**",
        "",
        r"$$F_{Sn}=0.6R_{mn}A_{Sn}C_1C_3$$",
        f"- 代入：0.6 × {Rmn:.9f} × {r['ASn']:.9f} × {r['C1']:.12f} × {r['C3']:.12f}",
        f"- **FSn = {r['FSn']:.6f} N = {r['FSn']/1000:.6f} kN**",
        "",
        "## 8. 控制结果",
        "",
        f"- 螺栓断裂 FBb：`{r['FBb']/1000:.6f} kN`",
        f"- 外螺纹剥牙 FSb：`{r['FSb']/1000:.6f} kN`",
        f"- 内螺纹剥牙 FSn：`{r['FSn']/1000:.6f} kN`",
        f"- **控制失效模式：{governing_cn}**",
        f"- **控制失效载荷：{r['governing_load']/1000:.6f} kN**",
        f"- 安全系数：`{safety_factor:.6f}`",
        "",
        r"$$F_{allow}=\frac{F_{governing}}{n}$$",
        f"- **安全系数后允许载荷：{r['allowable_load']/1000:.6f} kN**",
        "",
        "## 9. 适用范围警告",
        "",
    ]

    if r["warnings"]:
        if not applied_c1:
            lines.append("> **警告：C1 超出标准给定适用范围，本次未采用 C1 修正（C1=1.0）。**")
        if not applied_c2:
            lines.append("> **警告：C2 超出标准给定适用范围，本次未采用 C2 修正（C2=1.0）。**")
        if not applied_c3:
            lines.append("> **警告：C3 超出标准给定适用范围，本次未采用 C3 修正（C3=1.0）。**")
        lines.append("> **由于至少一个修正项超出标准给定范围，模型适用性和计算准确性降低。建议计算者根据工程风险增大安全系数，并结合试验或其他更适用的方法复核。**")
    else:
        lines.append("本次 C1、C2、C3 均处于程序采用的标准适用范围内，未触发修正项超限警告。")

    lines += [
        "",
        "## 10. 输出文件",
        "",
        f"- `{CASE_NAME}_drawing.pdf`：仅包含参数化工程图",
        f"- `{CASE_NAME}_calculation.md`：中文计算过程、公式、代入、结果和警告",
        "",
    ]
    return "\n".join(lines)


# ============================================================================
# 6. CAD-STYLE PDF DRAWING HELPERS
# ============================================================================

PAGE_W, PAGE_H = landscape(A3)

# Line weights in points, loosely following technical drawing conventions.
LW_OBJECT = 1.25
LW_THIN = 0.45
LW_DIM = 0.45
LW_CENTER = 0.35
LW_HATCH = 0.30


def ptx(x_mm):
    return x_mm * mm


def draw_centerline(c, x1, y1, x2, y2):
    c.saveState()
    c.setLineWidth(LW_CENTER)
    c.setDash([8, 3, 1.5, 3], 0)
    c.line(x1, y1, x2, y2)
    c.restoreState()


def arrow_head(c, x, y, angle, size=5.5):
    a = math.radians(24)
    x1 = x - size * math.cos(angle - a)
    y1 = y - size * math.sin(angle - a)
    x2 = x - size * math.cos(angle + a)
    y2 = y - size * math.sin(angle + a)
    p = c.beginPath()
    p.moveTo(x, y)
    p.lineTo(x1, y1)
    p.lineTo(x2, y2)
    p.close()
    c.drawPath(p, fill=1, stroke=0)


def dim_h(c, x1, x2, y_obj, y_dim, text, font_size=8):
    c.saveState()
    c.setLineWidth(LW_DIM)
    ext = 3.5
    c.line(x1, y_obj, x1, y_dim + (ext if y_dim >= y_obj else -ext))
    c.line(x2, y_obj, x2, y_dim + (ext if y_dim >= y_obj else -ext))
    c.line(x1, y_dim, x2, y_dim)
    arrow_head(c, x1, y_dim, 0)
    arrow_head(c, x2, y_dim, math.pi)
    c.setFont("Helvetica", font_size)
    tw = c.stringWidth(text, "Helvetica", font_size)
    gap = 4
    c.setFillColorRGB(1, 1, 1)
    c.rect((x1+x2-tw)/2-gap, y_dim-font_size*0.45, tw+2*gap, font_size*1.15, fill=1, stroke=0)
    c.setFillColorRGB(0, 0, 0)
    c.drawCentredString((x1+x2)/2, y_dim-font_size*0.3, text)
    c.restoreState()


def dim_v(c, y1, y2, x_obj, x_dim, text, font_size=8):
    c.saveState()
    c.setLineWidth(LW_DIM)
    ext = 3.5
    c.line(x_obj, y1, x_dim + (ext if x_dim >= x_obj else -ext), y1)
    c.line(x_obj, y2, x_dim + (ext if x_dim >= x_obj else -ext), y2)
    c.line(x_dim, y1, x_dim, y2)
    arrow_head(c, x_dim, y1, math.pi/2)
    arrow_head(c, x_dim, y2, -math.pi/2)
    c.setFont("Helvetica", font_size)
    c.saveState()
    c.translate(x_dim-font_size*0.35, (y1+y2)/2)
    c.rotate(90)
    tw = c.stringWidth(text, "Helvetica", font_size)
    gap = 4
    c.setFillColorRGB(1, 1, 1)
    c.rect(-tw/2-gap, -font_size*0.42, tw+2*gap, font_size*1.12, fill=1, stroke=0)
    c.setFillColorRGB(0, 0, 0)
    c.drawCentredString(0, -font_size*0.3, text)
    c.restoreState()
    c.restoreState()


def leader(c, x0, y0, x1, y1, x2, text, font_size=8):
    c.saveState()
    c.setLineWidth(LW_DIM)
    c.line(x0, y0, x1, y1)
    c.line(x1, y1, x2, y1)
    arrow_head(c, x0, y0, math.atan2(y0-y1, x0-x1))
    c.setFont("Helvetica", font_size)
    c.drawString(x2+4, y1-font_size*0.3, text)
    c.restoreState()


def draw_polyline(c, pts, line_width=LW_OBJECT):
    c.saveState()
    c.setLineWidth(line_width)
    for a, b in zip(pts[:-1], pts[1:]):
        c.line(a[0], a[1], b[0], b[1])
    c.restoreState()


def draw_angle_dim(c, cx, cy, radius, angle_deg, text=None, apex_up=True, font_size=8):
    """
    Draw an included-angle arc that follows the user-input thread angle.
    """
    c.saveState()
    c.setLineWidth(LW_DIM)
    n = 32
    pts = []
    if apex_up:
        for i in range(n + 1):
            phi = math.radians(-angle_deg / 2.0 + angle_deg * i / n)
            x = cx + radius * math.sin(phi)
            y = cy - radius * math.cos(phi)
            pts.append((x, y))
    else:
        for i in range(n + 1):
            phi = math.radians(-angle_deg / 2.0 + angle_deg * i / n)
            x = cx + radius * math.sin(phi)
            y = cy + radius * math.cos(phi)
            pts.append((x, y))
    for a, b in zip(pts[:-1], pts[1:]):
        c.line(a[0], a[1], b[0], b[1])
    p0, p1 = pts[0], pts[1]
    pn1, pn = pts[-2], pts[-1]
    arrow_head(c, p0[0], p0[1], math.atan2(p0[1]-p1[1], p0[0]-p1[0]))
    arrow_head(c, pn[0], pn[1], math.atan2(pn[1]-pn1[1], pn[0]-pn1[0]))
    if text is None:
        text = f"{angle_deg:.1f}°"
    mid = pts[len(pts)//2]
    c.setFont("Helvetica", font_size)
    c.drawCentredString(mid[0], mid[1] + (9 if not apex_up else -9), text)
    c.restoreState()


def draw_h_helper(c, x1, x2, y, label=None, label_side="left"):
    c.saveState()
    c.setLineWidth(LW_THIN)
    c.line(x1, y, x2, y)
    if label:
        c.setFont("Helvetica", 7.5)
        if label_side == "left":
            c.drawRightString(x1-4, y-2.0, label)
        else:
            c.drawString(x2+4, y-2.0, label)
    c.restoreState()


def draw_v_helper(c, x, y1, y2, dashed=True):
    c.saveState()
    c.setLineWidth(LW_CENTER if dashed else LW_THIN)
    if dashed:
        c.setDash([5, 3], 0)
    c.line(x, y1, x, y2)
    c.restoreState()


def external_root_fillet_geometry(g):
    """
    根据用户输入的牙型角和 h_external_root 构造与两侧理论牙面相切的圆弧。

    设 t = alpha/2，h_r = h_external_root：
        rho = h_r*sin(t)/(1-sin(t))

    对 alpha=60° 且 h_r=H/6，有 rho=H/6。
    """
    t = math.radians(thread_angle / 2.0)
    sin_t = math.sin(t)
    cos_t = math.cos(t)

    if sin_t <= 0.0 or sin_t >= 1.0:
        raise ValueError("无法为当前 thread_angle 构造有限的外螺纹牙底相切圆弧")

    h_r = g["h_external_root"]
    rho = h_r * sin_t / (1.0 - sin_t)

    theoretical_root_depth = g["H"] - g["h_flat"]
    bottom_depth = theoretical_root_depth - h_r
    center_depth = bottom_depth - rho

    x_tangent = rho * cos_t
    tangent_depth = center_depth + rho * sin_t

    return {
        "rho": rho,
        "theoretical_root_depth": theoretical_root_depth,
        "bottom_depth": bottom_depth,
        "center_depth": center_depth,
        "x_tangent": x_tangent,
        "tangent_depth": tangent_depth,
    }


def draw_external_root_arc(c, x_mid, y_of_depth, scale, fillet):
    """绘制真实圆弧；最低点位于 d3 深度，且与两侧牙面相切。"""
    rho_p = fillet["rho"] * scale
    center_y = y_of_depth(fillet["center_depth"])

    x1 = x_mid - rho_p
    y1 = center_y - rho_p
    x2 = x_mid + rho_p
    y2 = center_y + rho_p

    t_deg = thread_angle / 2.0
    start_angle = 180.0 + t_deg
    extent = 180.0 - thread_angle

    c.saveState()
    c.setLineWidth(LW_OBJECT)
    c.arc(x1, y1, x2, y2, startAng=start_angle, extent=extent)
    c.restoreState()


def hatch_rect(c, x, y, w, h, spacing=7, angle=45):
    c.saveState()
    path = c.beginPath()
    path.rect(x, y, w, h)
    c.clipPath(path, stroke=0, fill=0)
    c.setLineWidth(LW_HATCH)
    # 45-degree hatch family; enough for technical section indication.
    span = w + h + 100
    start = x - h - 50
    t = start
    while t < x + w + 50:
        c.line(t, y-20, t+h+60, y+h+40)
        t += spacing
    c.restoreState()



def hatch_polygon(c, points, spacing=8):
    """Clip hatch lines to a polygon for a cleaner sectional CAD appearance."""
    c.saveState()
    p = c.beginPath()
    p.moveTo(points[0][0], points[0][1])
    for x, y in points[1:]:
        p.lineTo(x, y)
    p.close()
    c.clipPath(p, stroke=0, fill=0)
    c.setLineWidth(LW_HATCH)
    xs = [q[0] for q in points]
    ys = [q[1] for q in points]
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = min(ys), max(ys)
    span = (xmax-xmin) + (ymax-ymin) + 60
    t = xmin - (ymax-ymin) - 40
    while t < xmax + 40:
        c.line(t, ymin-20, t+span, ymin-20+span)
        t += spacing
    c.restoreState()

def draw_title_block(c, case_name, subtitle):
    x0 = PAGE_W - 135*mm
    y0 = 10*mm
    w = 125*mm
    h = 26*mm
    c.setLineWidth(LW_THIN)
    c.rect(x0, y0, w, h)
    c.line(x0, y0+13*mm, x0+w, y0+13*mm)
    c.line(x0+72*mm, y0, x0+72*mm, y0+h)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(x0+4*mm, y0+17*mm, "ISO/TR 16224 PARAMETRIC DRAWING")
    c.setFont("Helvetica", 8)
    c.drawString(x0+4*mm, y0+5*mm, f"CASE: {case_name}")
    c.drawString(x0+76*mm, y0+17*mm, "SCALE: NTS")
    c.drawString(x0+76*mm, y0+5*mm, subtitle)


def draw_nut_section_page(c, r):
    """Page 1: clean axial section with CAD-like line weights and dimensions."""
    g = r["g"]
    mval = r["m"]
    meff = r["meff"]

    c.setFont("Helvetica-Bold", 14)
    c.drawString(18*mm, PAGE_H-18*mm, "NUT AXIAL SECTION - PARAMETRIC DESIGN VIEW")
    c.setFont("Helvetica", 8)
    c.drawRightString(PAGE_W-18*mm, PAGE_H-18*mm, "All dimensions in mm")

    # Keep a generous left/right dimension zone.
    available_w = 165*mm
    available_h = 165*mm
    scale = min(available_w/(s*mm), available_h/(mval*mm), 4.0)

    cx = 155*mm
    cy = 82*mm
    nut_w = s*mm*scale
    nut_h = mval*mm*scale
    xL, xR = cx-nut_w/2, cx+nut_w/2
    yB, yT = cy, cy+nut_h

    D1w = g["D1"]*mm*scale
    D2w = g["D2"]*mm*scale
    Dw = g["D"]*mm*scale
    xD1L, xD1R = cx-D1w/2, cx+D1w/2
    xD2L, xD2R = cx-D2w/2, cx+D2w/2
    xDL, xDR = cx-Dw/2, cx+Dw/2

    # Section hatching and outer contour.
    hatch_rect(c, xL, yB, xD1L-xL, nut_h, spacing=7)
    hatch_rect(c, xD1R, yB, xR-xD1R, nut_h, spacing=7)
    c.setLineWidth(LW_OBJECT)
    c.rect(xL, yB, nut_w, nut_h)

    # Conventional internal thread representation: crests thick, roots thin.
    c.setLineWidth(LW_OBJECT)
    c.line(xD1L, yB, xD1L, yT)
    c.line(xD1R, yB, xD1R, yT)
    c.setLineWidth(LW_THIN)
    c.line(xDL, yB+4*mm, xDL, yT-4*mm)
    c.line(xDR, yB+4*mm, xDR, yT-4*mm)
    c.setDash(4, 2)
    c.line(xD2L, yB+4*mm, xD2L, yT-4*mm)
    c.line(xD2R, yB+4*mm, xD2R, yT-4*mm)
    c.setDash()

    # Chamfer geometry if hc > 0.
    if hc > 0:
        theta = math.radians(drawing_countersink_included_angle/2)
        radial = hc*math.tan(theta)*mm*scale
        hcp = hc*mm*scale
        c.setLineWidth(LW_OBJECT)
        c.line(xD1L, yT-hcp, xD1L-radial, yT)
        c.line(xD1R, yT-hcp, xD1R+radial, yT)
        if chamfer_ends == 2:
            c.line(xD1L, yB+hcp, xD1L-radial, yB)
            c.line(xD1R, yB+hcp, xD1R+radial, yB)

    draw_centerline(c, cx, yB-14*mm, cx, yT+16*mm)

    # Dimension bands: no shared text area, no overlaps.
    dim_h(c, xL, xR, yB, yB-20*mm, f"s = {s:.3f}")
    dim_h(c, xD1L, xD1R, yB, yB-36*mm, f"D1 = {g['D1']:.3f}")

    dim_v(c, yB, yT, xL, xL-18*mm, f"m = {mval:.3f}")
    if not math.isclose(meff, mval, abs_tol=1e-9):
        dim_v(c, yB, yB+meff*mm*scale, xL, xL-34*mm, f"meff = {meff:.3f}")
    else:
        c.setFont("Helvetica", 8)
        c.drawString(xL-46*mm, yB+nut_h*0.48, f"meff = m = {meff:.3f}")

    # Fixed right annotation column.
    ann_x = 295*mm
    ys = [yT-25*mm, yT-50*mm, yT-75*mm]
    leader(c, xD1R, yT-0.30*nut_h, xR+12*mm, ys[0], ann_x, f"D1 = {g['D1']:.3f}")
    leader(c, xD2R, yT-0.50*nut_h, xR+12*mm, ys[1], ann_x, f"D2 = {g['D2']:.3f}")
    leader(c, xDR,   yT-0.70*nut_h, xR+12*mm, ys[2], ann_x, f"D = d = {g['D']:.3f}")

    if hc > 0:
        dim_v(c, yT-hc*mm*scale, yT, xR, xR+45*mm, f"hc = {hc:.3f}")

    # Drawing notes only; calculations remain in MD.
    c.setFont("Helvetica", 8)
    c.drawString(18*mm, 49*mm, f"Nut height mode: {nut_height_mode}")
    c.drawString(18*mm, 43*mm, f"m = {nut_height_ratio:.3f} D" if nut_height_mode == "ratio" else "m = custom input")
    c.drawString(18*mm, 37*mm, "Internal thread: crest thick line, root thin line; D2 dashed as reference.")

    draw_title_block(c, CASE_NAME, "SHEET 1/2")
    c.showPage()



def draw_thread_profile_page(c, r):
    """
    Page 2:
    - 保留水平辅助线、理论包络线和节距竖向构造线；
    - x/y 采用相同比例，确保牙型夹角按用户输入角度真实绘制；
    - 外螺纹牙底采用与两侧牙面严格相切的圆弧。
    """
    g = r["g"]
    fillet = external_root_fillet_geometry(g)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(18*mm, PAGE_H-18*mm, "THREAD GEOMETRY DETAIL - PARAMETRIC CAD CONSTRUCTION")
    c.setFont("Helvetica", 8)
    c.drawRightString(PAGE_W-18*mm, PAGE_H-18*mm, "All dimensions in mm")

    x0 = 92*mm
    n_pitch = 2

    # x/y 使用相同几何比例，避免角度显示失真。
    geom_scale = min(46*mm/P, 48*mm/g["H"])
    x_end = x0 + n_pitch * P * geom_scale

    crest_half = g["h_flat"] * g["tan_half"] * geom_scale
    int_crest_half = g["h_internal_crest"] * g["tan_half"] * geom_scale

    d_depth = 0.0
    d2_depth = (g["d"] - g["d2"]) / 2.0
    D1_depth = (g["d"] - g["D1"]) / 2.0
    d3_depth = (g["d"] - g["d3"]) / 2.0
    theoretical_root_depth = fillet["theoretical_root_depth"]

    # -------------------- INTERNAL THREAD --------------------
    c.setFont("Helvetica-Bold", 10)
    c.drawString(22*mm, 224*mm, "INTERNAL THREAD - REFERENCE / CONSTRUCTION LINES")
    c.setFont("Helvetica", 7.8)
    c.drawString(22*mm, 217*mm, f"Displayed flank angle = user input alpha = {thread_angle:.3f} deg.")

    y_major = 188*mm
    yi = lambda depth: y_major - depth * geom_scale

    draw_h_helper(c, x0-18*mm, x_end+10*mm, yi(d_depth), "D")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, yi(d2_depth), "D2")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, yi(D1_depth), "D1")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, yi(-g["h_flat"]), "theoretical crest")

    for i in range(2*n_pitch + 1):
        xv = x0 + i*(P*geom_scale/2.0)
        draw_v_helper(c, xv, yi(D1_depth)-10*mm, yi(-g["h_flat"])+8*mm, dashed=True)

    int_pts = []
    for i in range(n_pitch):
        crest_center = x0 + i*P*geom_scale
        valley_center = crest_center + P*geom_scale/2.0
        next_crest = crest_center + P*geom_scale

        pts = [
            (crest_center, yi(d_depth)),
            (crest_center + crest_half, yi(d_depth)),
            (valley_center - int_crest_half, yi(D1_depth)),
            (valley_center + int_crest_half, yi(D1_depth)),
            (next_crest - crest_half, yi(d_depth)),
            (next_crest, yi(d_depth)),
        ]
        if i:
            pts = pts[1:]
        int_pts.extend(pts)

    top_y = yi(-g["h_flat"]) + 18*mm
    int_poly = int_pts + [(x_end+8*mm, top_y), (x0-8*mm, top_y)]
    hatch_polygon(c, int_poly, spacing=8)
    draw_polyline(c, int_pts, LW_OBJECT)

    c.saveState()
    c.setLineWidth(LW_THIN)
    for i in range(n_pitch):
        crest_center = x0 + i*P*geom_scale
        next_crest = crest_center + P*geom_scale
        valley = crest_center + P*geom_scale/2.0
        c.line(crest_center, yi(-g["h_flat"]), valley, yi(theoretical_root_depth))
        c.line(valley, yi(theoretical_root_depth), next_crest, yi(-g["h_flat"]))
    c.restoreState()

    dim_h(c, x0, x0+P*geom_scale, yi(D1_depth), yi(D1_depth)-18*mm, f"P = {P:.3f}")
    dim_h(c, x0, x0+0.5*P*geom_scale, yi(D1_depth), yi(D1_depth)-31*mm, f"P/2 = {P/2.0:.3f}")

    crest_angle_x = x0 + P*geom_scale
    draw_angle_dim(
        c,
        crest_angle_x,
        yi(-g["h_flat"]),
        min(13*mm, 0.24*g["H"]*geom_scale),
        thread_angle,
        f"{thread_angle:.2f}°",
        apex_up=True,
    )

    rx = 292*mm
    leader(c, x_end+2*mm, yi(d_depth), x_end+18*mm, 202*mm, rx, f"D = {g['D']:.3f}")
    leader(c, x_end+2*mm, yi(d2_depth), x_end+18*mm, 191*mm, rx, f"D2 = {g['D2']:.3f}")
    leader(c, x_end+2*mm, yi(D1_depth), x_end+18*mm, 180*mm, rx, f"D1 = {g['D1']:.3f}")

    # -------------------- EXTERNAL THREAD --------------------
    c.setFont("Helvetica-Bold", 10)
    c.drawString(22*mm, 110*mm, "EXTERNAL THREAD - TRUE TANGENT ROOT FILLET")
    c.setFont("Helvetica", 7.8)
    c.drawString(
        22*mm,
        103*mm,
        f"Root arc tangent to both flanks; alpha={thread_angle:.3f} deg, rho={fillet['rho']:.5f} mm."
    )

    y_major2 = 80*mm
    ye = lambda depth: y_major2 - depth*geom_scale

    draw_h_helper(c, x0-18*mm, x_end+10*mm, ye(d_depth), "d")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, ye(d2_depth), "d2")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, ye(d3_depth), "d3")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, ye(-g["h_flat"]), "theoretical crest")
    draw_h_helper(c, x0-18*mm, x_end+10*mm, ye(theoretical_root_depth), "theoretical sharp root")

    for i in range(2*n_pitch + 1):
        xv = x0 + i*(P*geom_scale/2.0)
        draw_v_helper(c, xv, ye(theoretical_root_depth)-8*mm, ye(-g["h_flat"])+8*mm, dashed=True)

    # theoretical V construction
    c.saveState()
    c.setLineWidth(LW_THIN)
    for i in range(n_pitch):
        crest_center = x0 + i*P*geom_scale
        valley_center = crest_center + P*geom_scale/2.0
        next_crest = crest_center + P*geom_scale
        c.line(crest_center, ye(-g["h_flat"]), valley_center, ye(theoretical_root_depth))
        c.line(valley_center, ye(theoretical_root_depth), next_crest, ye(-g["h_flat"]))
    c.restoreState()

    # actual external profile with exact tangent circular fillet
    c.saveState()
    c.setLineWidth(LW_OBJECT)
    for i in range(n_pitch):
        crest_center = x0 + i*P*geom_scale
        next_crest = crest_center + P*geom_scale
        valley_center = crest_center + P*geom_scale/2.0

        crest_right = crest_center + crest_half
        next_crest_left = next_crest - crest_half

        x_tan = fillet["x_tangent"] * geom_scale
        left_tangent_x = valley_center - x_tan
        right_tangent_x = valley_center + x_tan
        tangent_y = ye(fillet["tangent_depth"])

        c.line(crest_center, ye(0.0), crest_right, ye(0.0))
        c.line(next_crest_left, ye(0.0), next_crest, ye(0.0))
        c.line(crest_right, ye(0.0), left_tangent_x, tangent_y)
        c.line(right_tangent_x, tangent_y, next_crest_left, ye(0.0))

        draw_external_root_arc(c, valley_center, ye, geom_scale, fillet)
    c.restoreState()

    dim_h(c, x0, x0+P*geom_scale, ye(theoretical_root_depth), ye(theoretical_root_depth)-16*mm, f"P = {P:.3f}")
    dim_h(c, x0, x0+0.5*P*geom_scale, ye(theoretical_root_depth), ye(theoretical_root_depth)-29*mm, f"P/2 = {P/2.0:.3f}")
    dim_v(c, ye(theoretical_root_depth), ye(-g["h_flat"]), x_end+10*mm, x_end+24*mm, f"H = {g['H']:.3f}")

    crest_angle_x = x0 + P*geom_scale
    draw_angle_dim(
        c,
        crest_angle_x,
        ye(-g["h_flat"]),
        min(13*mm, 0.24*g["H"]*geom_scale),
        thread_angle,
        f"{thread_angle:.2f}°",
        apex_up=True,
    )

    rx2 = 292*mm
    leader(c, x_end+2*mm, ye(d_depth), x_end+18*mm, 92*mm, rx2, f"d = {g['d']:.3f}")
    leader(c, x_end+2*mm, ye(d2_depth), x_end+18*mm, 81*mm, rx2, f"d2 = {g['d2']:.3f}")
    leader(c, x_end+2*mm, ye(d3_depth), x_end+18*mm, 70*mm, rx2, f"d3 = {g['d3']:.3f}")

    c.setFont("Helvetica-Bold", 8)
    c.drawString(22*mm, 18*mm, "PROFILE INPUTS / DRAWING GEOMETRY")
    c.setFont("Helvetica", 7.5)
    c.drawString(22*mm, 12*mm, f"k_flat={k_flat:.6f}; h_flat={g['h_flat']:.4f} mm")
    c.drawString(85*mm, 12*mm, f"k_external_root={k_external_root:.6f}; h_ext.root={g['h_external_root']:.4f} mm")
    c.drawString(185*mm, 12*mm, f"root radius rho={fillet['rho']:.5f} mm; angle={thread_angle:.3f} deg")

    draw_title_block(c, CASE_NAME, "SHEET 2/2")
    c.showPage()


def generate_drawing_pdf(r, pdf_path):
    c = canvas.Canvas(str(pdf_path), pagesize=landscape(A3))
    c.setTitle(f"{CASE_NAME} - ISO/TR 16224 parametric drawing")
    draw_nut_section_page(c, r)
    draw_thread_profile_page(c, r)
    c.save()


# ============================================================================
# 7. OUTPUT
# ============================================================================

def main():
    r = calculate()

    case_dir = OUTPUT_BASE_DIR.expanduser() / CASE_NAME
    case_dir.mkdir(parents=True, exist_ok=True)

    pdf_path = case_dir / f"{CASE_NAME}_drawing.pdf"
    md_path = case_dir / f"{CASE_NAME}_calculation.md"

    generate_drawing_pdf(r, pdf_path)
    md_path.write_text(build_markdown(r), encoding="utf-8")

    print("=" * 72)
    print("ISO/TR 16224 V13 complete")
    print("Python/ReportLab compatibility: hashlib.md5 usedforsecurity shim enabled")
    print("=" * 72)
    print(f"Case folder : {case_dir.resolve()}")
    print(f"Drawing PDF : {pdf_path.resolve()}")
    print(f"Calculation : {md_path.resolve()}")
    print(f"m           : {r['m']:.6f} mm ({nut_height_mode})")
    print(f"FBb         : {r['FBb']/1000:.6f} kN")
    print(f"FSb         : {r['FSb']/1000:.6f} kN")
    print(f"FSn         : {r['FSn']/1000:.6f} kN")
    print(f"Allowable   : {r['allowable_load']/1000:.6f} kN")
    if r["warnings"]:
        print("Warnings:")
        for w in r["warnings"]:
            print(" -", w)


if __name__ == "__main__":
    main()
